name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-north2-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t europe-north2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tns-backend-github-deploy/tns-backend:${{ github.sha }} .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push europe-north2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tns-backend-github-deploy/tns-backend:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tns-backend \
            --image europe-north2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tns-backend-github-deploy/tns-backend:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Show service URL
        run: |
          gcloud run services describe tns-backend \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --format 'value(status.url)' \
            --project ${{ secrets.GCP_PROJECT_ID }}
